name: Deploy to firebase
on:
  push:
    branches: [ main ]
    
jobs:
  # the action to automatically deploy react app to firebase hosting
  build_and_deploy_hosting:
    name: Build and Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Make envfile
        uses: SpicyPizza/create-envfile@main
        with:
          envkey_VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}
          envkey_VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          envkey_VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          envkey_VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          envkey_VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          envkey_VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          envkey_VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          envkey_VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          directory: app
          file_name: .env

      - name: Install Dependencies
        run: yarn --cwd app install --frozen-lockfile

      - name: Build
        run: yarn --cwd app build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  # the action to automatically deploy firestore rules
  deploy_firestore:
    name: Deploy Firestore Rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  # the action to automatically deploy firebase storage rules
  deploy_storage:
    name: Deploy Cloud Storage Rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only storage --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
